language: php

php:
  - 7.0
  - 7.1
  - 7.2
  
install: php vendor/vendors.php
  
before_script:
  - phpenv config-add phpconfig.ini
  - composer self-update
  - composer update

script:
  - composer test